web:
    image: nginx:latest
    ports:
        - "8088:80"
    volumes:
        - ./www:/www
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    build: ./docker/php
    dockerfile: Dockerfile
    volumes:
        - ./www:/www
    links:
        - db

db:
  image: mysql:5.7
  volumes:
    - ./db:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: basic
    MYSQL_USER: root
    MYSQL_PASSWORD: root